#!/usr/bin/env bash

# Date: 2019-06-30
# Author: Woods Wannamaker
# Purpose: restore original dotfiles from backup (.dtbak) file
# Source: Modified from
# https://github.com/flipsidecreations/dotfiles/blob/master/uninstall.sh

dotfiles=( ".bash_aliases" ".bash_functions" ".bashrc" ".tmux.conf" ".vimrc" )

main () {
    for file in "${dotfiles[@]}"
    do
        if [ -h ~/$file ]; then
        rm -f ~/$file
        fi
        
        if [ -e ~/${file}.dtbak ]; then
        mv -f ~/$file{.dtbak,}
        fi
    done
    printf "\nFiles restored\n\n"
}

if [ "$(basename "$PWD")" = "dotfiles" ]
then
    main
else
    printf "\n%s\n\n" "Error! Run script from the dotfiles directory."
    exit  
fi
